services:
  - type: web
    name: cancer-cell-detection-frontend
    env: node
    buildCommand: pnpm install && pnpm build
    startCommand: pnpm start
    envVars:
      - key: NODE_VERSION
        value: 18.0.0
      - key: NEXT_PUBLIC_API_URL
        value: https://cancer-cell-detection-backend.onrender.com 